# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/j.mertens/github/jmLightCreator/src/resources/ui/jmLightCreatorUI.ui'
#
# Created: Thu May 23 14:49:15 2019
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_widget_root(object):
    def setupUi(self, widget_root):
        widget_root.setObjectName("widget_root")
        widget_root.resize(128, 260)
        self.verticalLayout = QtWidgets.QVBoxLayout(widget_root)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_button = QtWidgets.QGridLayout()
        self.gridLayout_button.setSpacing(3)
        self.gridLayout_button.setObjectName("gridLayout_button")
        self.pushButton_aiSkyDomeLight = QtWidgets.QPushButton(widget_root)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_aiSkyDomeLight.sizePolicy().hasHeightForWidth())
        self.pushButton_aiSkyDomeLight.setSizePolicy(sizePolicy)
        self.pushButton_aiSkyDomeLight.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_aiSkyDomeLight.setText("")
        self.pushButton_aiSkyDomeLight.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_aiSkyDomeLight.setObjectName("pushButton_aiSkyDomeLight")
        self.gridLayout_button.addWidget(self.pushButton_aiSkyDomeLight, 2, 2, 1, 1)
        self.pushButton_aiAreaLight = QtWidgets.QPushButton(widget_root)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_aiAreaLight.sizePolicy().hasHeightForWidth())
        self.pushButton_aiAreaLight.setSizePolicy(sizePolicy)
        self.pushButton_aiAreaLight.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_aiAreaLight.setText("")
        self.pushButton_aiAreaLight.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_aiAreaLight.setObjectName("pushButton_aiAreaLight")
        self.gridLayout_button.addWidget(self.pushButton_aiAreaLight, 2, 1, 1, 1)
        self.pushButton_directionalLight = QtWidgets.QPushButton(widget_root)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_directionalLight.sizePolicy().hasHeightForWidth())
        self.pushButton_directionalLight.setSizePolicy(sizePolicy)
        self.pushButton_directionalLight.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_directionalLight.setText("")
        self.pushButton_directionalLight.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_directionalLight.setObjectName("pushButton_directionalLight")
        self.gridLayout_button.addWidget(self.pushButton_directionalLight, 1, 2, 1, 1)
        self.pushButton_pointLight = QtWidgets.QPushButton(widget_root)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_pointLight.sizePolicy().hasHeightForWidth())
        self.pushButton_pointLight.setSizePolicy(sizePolicy)
        self.pushButton_pointLight.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_pointLight.setText("")
        self.pushButton_pointLight.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_pointLight.setObjectName("pushButton_pointLight")
        self.gridLayout_button.addWidget(self.pushButton_pointLight, 2, 0, 1, 1)
        self.pushButton_spotLight = QtWidgets.QPushButton(widget_root)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_spotLight.sizePolicy().hasHeightForWidth())
        self.pushButton_spotLight.setSizePolicy(sizePolicy)
        self.pushButton_spotLight.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_spotLight.setText("")
        self.pushButton_spotLight.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_spotLight.setObjectName("pushButton_spotLight")
        self.gridLayout_button.addWidget(self.pushButton_spotLight, 1, 1, 1, 1)
        self.comboBox_function = QtWidgets.QComboBox(widget_root)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_function.sizePolicy().hasHeightForWidth())
        self.comboBox_function.setSizePolicy(sizePolicy)
        self.comboBox_function.setMinimumSize(QtCore.QSize(40, 30))
        self.comboBox_function.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_function.setFont(font)
        self.comboBox_function.setObjectName("comboBox_function")
        self.gridLayout_button.addWidget(self.comboBox_function, 1, 0, 1, 1)
        self.lineEdit_basename = QtWidgets.QLineEdit(widget_root)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_basename.sizePolicy().hasHeightForWidth())
        self.lineEdit_basename.setSizePolicy(sizePolicy)
        self.lineEdit_basename.setMinimumSize(QtCore.QSize(40, 30))
        self.lineEdit_basename.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_basename.setObjectName("lineEdit_basename")
        self.gridLayout_button.addWidget(self.lineEdit_basename, 0, 2, 1, 1)
        self.pushButton_selected = QtWidgets.QPushButton(widget_root)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_selected.sizePolicy().hasHeightForWidth())
        self.pushButton_selected.setSizePolicy(sizePolicy)
        self.pushButton_selected.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_selected.setText("")
        self.pushButton_selected.setCheckable(True)
        self.pushButton_selected.setObjectName("pushButton_selected")
        self.gridLayout_button.addWidget(self.pushButton_selected, 0, 1, 1, 1)
        self.pushButton_illuminate = QtWidgets.QPushButton(widget_root)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_illuminate.sizePolicy().hasHeightForWidth())
        self.pushButton_illuminate.setSizePolicy(sizePolicy)
        self.pushButton_illuminate.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_illuminate.setText("")
        self.pushButton_illuminate.setCheckable(True)
        self.pushButton_illuminate.setObjectName("pushButton_illuminate")
        self.gridLayout_button.addWidget(self.pushButton_illuminate, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_button)

        self.retranslateUi(widget_root)
        QtCore.QMetaObject.connectSlotsByName(widget_root)

    def retranslateUi(self, widget_root):
        self.pushButton_aiSkyDomeLight.setToolTip(QtWidgets.QApplication.translate("widget_root", "<html><head/><body><p>aiSkyDomeLight</p></body></html>", None, -1))
        self.pushButton_aiAreaLight.setToolTip(QtWidgets.QApplication.translate("widget_root", "<html><head/><body><p>aiAreaLight</p></body></html>", None, -1))
        self.pushButton_directionalLight.setToolTip(QtWidgets.QApplication.translate("widget_root", "<html><head/><body><p>directionalLight</p></body></html>", None, -1))
        self.pushButton_pointLight.setToolTip(QtWidgets.QApplication.translate("widget_root", "<html><head/><body><p>pointLight</p></body></html>", None, -1))
        self.pushButton_spotLight.setToolTip(QtWidgets.QApplication.translate("widget_root", "<html><head/><body><p>spotLight</p></body></html>", None, -1))
        self.pushButton_selected.setToolTip(QtWidgets.QApplication.translate("widget_root", "<html><head/><body><p>Lightname from selected</p></body></html>", None, -1))
        self.pushButton_illuminate.setToolTip(QtWidgets.QApplication.translate("widget_root", "<html><head/><body><p>Lightname from selected</p></body></html>", None, -1))

